config/routes.rb
Rails.application.routes.draw do
  resources :categories
  resources :ingredients
  resources :dishes
  resources :restaurants do
    collection do
      get 'homepage'
      post 'homepage'
    end
  end

  root 'restaurants#homepage'
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/dish.rb
class Dish < ApplicationRecord
  validates_presence_of :name, :price, :cooktime

    belongs_to :restaurant
    belongs_to :category
    has_and_belongs_to_many :ingredients
end

app/controllers/dishes_controller.rb
class DishesController < ApplicationController
  before_action :set_dish, only: [:show, :edit, :update, :destroy]

  # GET /dishes
  # GET /dishes.json
  def index
    @dishes = Dish.all
  end

  # GET /dishes/1
  # GET /dishes/1.json
  def show
  end

  # GET /dishes/new
  def new
    @dish = Dish.new
  end

  # GET /dishes/1/edit
  def edit
  end

  # POST /dishes
  # POST /dishes.json
  def create
    @dish = Dish.new(dish_params)

    respond_to do |format|
      if @dish.save
        format.html { redirect_to @dish, notice: 'Dish was successfully created.' }
        format.json { render :show, status: :created, location: @dish }
      else
        format.html { render :new }
        format.json { render json: @dish.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /dishes/1
  # PATCH/PUT /dishes/1.json
  def update
    respond_to do |format|
      if @dish.update(dish_params)
        format.html { redirect_to @dish, notice: 'Dish was successfully updated.' }
        format.json { render :show, status: :ok, location: @dish }
      else
        format.html { render :edit }
        format.json { render json: @dish.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /dishes/1
  # DELETE /dishes/1.json
  def destroy
    @dish.destroy
    respond_to do |format|
      format.html { redirect_to dishes_url, notice: 'Dish was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_dish
      @dish = Dish.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def dish_params
      params.require(:dish).permit(:restaurant_id, :category_id, :name, :price, :cooktime, {ingredient_ids: []})
    end
end

app/helpers/dishes_helper.rb
module DishesHelper
end

app/views/dishes/_form.html.erb
<%= form_with(model: dish, local: true, :class => "form-group") do |form| %>

  <% if dish.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(dish.errors.count, "error") %> prohibited this dish from being saved:</h2>

      <ul>
      <% dish.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>v
  <% end %>

  <div class="field form-group">
      <label>Restaurante</label>
      <%= form.select :restaurant_id, Restaurant.all.collect {|restaurant| [restaurant.name, restaurant.id]}, :class => "form-control" %>
    </div>

    <div class="form-group">
      <%= form.label :ingredient_id %>
      <% for ingredient in Ingredient.all %>
       <%= check_box_tag "dish[ingredient_ids][]", ingredient.id, @dish.ingredients.include?(ingredient) %>
       <%= ingredient.name %>
   <% end %>
 </div>

    <div class="field form-group">
	   <%= form.label :category_id %>
	   <%= collection_select(:dish, :category_id, Category.all.collect, :id, :name, {}, class: 'form-control') %>
	 </div>

  <div class="field form-group">
    <label>Nome</label>
    <%= form.text_field :name, class: 'form-control' %>
  </div>

  <div class="field form-group">
    <label>Preço</label>
    <%= form.text_field :price, class: 'form-control' %>
  </div>

  <div class="field form-group">
    <label>Tempo de preparo</label>
    <%= form.time_select :cooktime, class: 'form-control' %>
  </div>

  <div class="actions">
    <%= form.submit %>
  </div>
<% end %>

app/views/dishes/edit.html.erb
<h1>Editing Dish</h1>

<%= render 'form', dish: @dish %>

<%= link_to 'Show', @dish, :class => "btn btn-warning" %>
<%= link_to 'Back', dishes_path, :class => "btn btn-warning" %>

app/views/dishes/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Dishes</h1>

<table>
  <thead>
    <tr>
      <th>Name</th>
      <th>Price</th>
      <th>Cooktime</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @dishes.each do |dish| %>
      <tr>
        <td><%= dish.name %></td>
        <td><%= dish.price %></td>
        <td><%= dish.cooktime %></td>
        <td><%= link_to 'Edit', edit_dish_path(dish), :class => "btn btn-warning" %></td>
        <td><%= link_to 'Destroy', dish, method: :delete, data: { confirm: 'Are you sure?' }, :class => "btn btn-warning" %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Dish', new_dish_path %>

app/views/dishes/new.html.erb
<h1>New Dish</h1>

<%= render 'form', dish: @dish %>

<%= link_to 'Back', dishes_path %>

app/views/dishes/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Name:</strong>
  <%= @dish.name %>
</p>

<p>
  <strong>Price:</strong>
  <%= @dish.price %>
</p>

<p>
  <strong>Cooktime:</strong>
  <%= @dish.cooktime %>
</p>

<%= link_to 'Edit', edit_dish_path(@dish), :class => "btn btn-warning" %>
<%= link_to 'Back', dishes_path, :class => "btn btn-warning" %>