config/routes.rb
Rails.application.routes.draw do
  resources :categories
  resources :ingredients
  resources :dishes
  resources :restaurants do
    collection do
      get 'homepage'
      post 'homepage'
    end
  end

  root 'restaurants#homepage'
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/restaurant.rb
class Restaurant < ApplicationRecord
  validates_presence_of :name, :phone, :address

  has_many :dishes
end

app/controllers/restaurants_controller.rb
class RestaurantsController < ApplicationController
  before_action :set_restaurant, only: [:show, :edit, :update, :destroy]

  # GET /restaurants
  # GET /restaurants.json
  def index
    @restaurants = Restaurant.all
  end

  def homepage
      @restaurants = Restaurant.order(:name)

      # categoria
      @restaurantsJoin = Restaurant.joins("INNER JOIN dishes ON dishes.restaurant_id = restaurants.id").distinct unless params[:category_id].blank?
      @restaurants = @restaurantsJoin.where("category_id = :category", {category: params[:category_id]}) unless params[:category_id].blank?

      # busca por termos
      @restaurants = Restaurant.joins(:dishes).where("UPPER(dishes.name) like ?" , "%#{params[:termo].upcase}%").order(:name) unless params[:termo].blank?
      #@restaurants = Restaurant.where('UPPER(name) LIKE ?', "%#{params[:termo].upcase}%") unless params[:termo].blank?
      #@restaurants = Restaurant.joins("INNER JOIN dishes ON dishes.restaurant_id = restaurants.id").distinct unless params[:termo].blank?

  end



  # GET /restaurants/1
  # GET /restaurants/1.json
  def show
    @ingredients = Ingredient.all
    @dishes = Dish.all # order(:description)
    @restaurants = Restaurant.order(:name)
    @ingredients = Ingredient.order(:name)
    @categories = Category.all
  end

  # GET /restaurants/new
  def new
    @restaurant = Restaurant.new
  end

  # GET /restaurants/1/edit
  def edit
  end

  # POST /restaurants
  # POST /restaurants.json
  def create
    @restaurant = Restaurant.new(restaurant_params)

    respond_to do |format|
      if @restaurant.save
        format.html { redirect_to @restaurant, notice: 'Restaurant was successfully created.' }
        format.json { render :show, status: :created, location: @restaurant }
      else
        format.html { render :new }
        format.json { render json: @restaurant.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /restaurants/1
  # PATCH/PUT /restaurants/1.json
  def update
    respond_to do |format|
      if @restaurant.update(restaurant_params)
        format.html { redirect_to @restaurant, notice: 'Restaurant was successfully updated.' }
        format.json { render :show, status: :ok, location: @restaurant }
      else
        format.html { render :edit }
        format.json { render json: @restaurant.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /restaurants/1
  # DELETE /restaurants/1.json
  def destroy
    @restaurant.destroy
    respond_to do |format|
      format.html { redirect_to restaurants_url, notice: 'Restaurant was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_restaurant
      @restaurant = Restaurant.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def restaurant_params
      params.require(:restaurant).permit(:name, :phone, :address)
    end
end

app/helpers/restaurants_helper.rb
module RestaurantsHelper
end

app/views/restaurants/_form.html.erb
<%= form_with(model: restaurant, local: true) do |form| %>
  <% if restaurant.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(restaurant.errors.count, "error") %> prohibited this restaurant from being saved:</h2>

      <ul>
      <% restaurant.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="form-group">
    <%= form.label :name %>
    <%= form.text_field :name, class: 'form-control' %>
  </div>

  <div class="form-group">
    <%= form.label :phone %>
    <%= form.text_field :phone, class: 'form-control' %>
  </div>

  <div class="form-group">
    <%= form.label :address %>
    <%= form.text_field :address, class: 'form-control' %>
  </div>

  <div class="actions">
    <%= form.submit %>
  </div>
<% end %>

app/views/restaurants/edit.html.erb
<h1>Editing Restaurant</h1>

<%= render 'form', restaurant: @restaurant %>

<%= link_to 'Show', @restaurant, :class => "btn btn-warning" %>
<%= link_to 'Back', restaurants_path, :class => "btn btn-warning" %>

app/views/restaurants/homepage.html.erb
<div class="row">
  <p id="notice"><%= notice %></p>
    <div id="restaurante" class="col-md-8 order-md-1">
      <% if not @restaurants.blank? %>
      <% @restaurants.each do |restaurant| %>
        <h2><%= link_to restaurant.name, restaurant %></h2>
        <hr>
      <% end %>
      <% else %>
        <h2 class="text-center">Nenhum restaurante encontrado.</h2>
      <% end %>
    </div>
    <div class="col-md-4 order-md-2 mb-4">
      <div class="panel panel-default">
        <div class="panel-heading">
          <h3 class="panel-title">Categories</h3>
        </div>
        <div class="panel-body">
          <ul>
            <% Category.all.each do |category| %>
              <li>
                <%= link_to category.name, homepage_restaurants_path(category_id: category.id) %>
              </li>
            <% end %>
          </ul>
        </div>
      </div>

      <div class="panel panel-default">
        <div class="panel-heading">
          <h3 class="panel-title">Search</h3>
        </div>
        <div class="panel-body">
          <%= form_tag('/restaurants/homepage', method: 'post') do %>
            <%= text_field_tag(:termo) %>
            <%= submit_tag('Buscar') %>
          <% end %>

        </div>
      </div>
    </div>
</div>

app/views/restaurants/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Restaurants</h1>

<table>
  <thead>
    <tr>
      <th>Name</th>
      <th>Phone</th>
      <th>Address</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @restaurants.each do |restaurant| %>
      <tr>
        <td><%= restaurant.name %></td>
        <td><%= restaurant.phone %></td>
        <td><%= restaurant.address %></td>
        <td><%= link_to 'Show', restaurant, :class => "btn btn-warning"%></td>
        <td><%= link_to 'Edit', edit_restaurant_path(restaurant), :class => "btn btn-warning" %></td>
        <td><%= link_to 'Destroy', restaurant, method: :delete, data: { confirm: 'Are you sure?' }, :class => "btn btn-warning" %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Restaurant', new_restaurant_path, :class => "btn btn-warning" %>

app/views/restaurants/new.html.erb
<h1>New Restaurant</h1>

<%= render 'form', restaurant: @restaurant %>

<%= link_to 'Back', restaurants_path %>

app/views/restaurants/show.html.erb
<p id="notice"><%= notice %></p>



<% if not @restaurant.dishes.blank? %>
      <% @restaurant.dishes.each do |dish| %>
        <div class="col-md-4">
        <div class="card mb-4 ">
          <div class="title card-body">

            <div class="Name">Name:<%= @restaurant.name %></div>
            <div class="Phone">Phone:<%= @restaurant.phone %></div>
            <div class="Address">Address:<%= @restaurant.address %></div>
            <div class="name">Categoria: <%= dish.category.name %></div>
            <div class="name">Prato: <%= dish.name %></div>
            <div class="price">R$: <b><%= dish.price %>0</b></div>
          </div>
          <div class="info">
            <% if not dish.ingredients.blank? %>

            <div class="ingredients">Ingredientes:
              <span><br/>
                   <ul>
                     <% dish.ingredients.each do | ingredient| %>
                     <li><%= ingredient.name%></li>
                     <% end %>
                   </ul>
                   </span>
            </div>
            <div class="cooktime"><b>Tempo de Preparo:</b> <%= dish.cooktime.strftime("%H:%M") %>h</div>
            <% end %>
          </div>

        </div>

        <%= link_to 'Edit', edit_restaurant_path(@restaurant), :class => "btn btn-warning" %>
        <%= link_to 'Back', restaurants_path, :class => "btn btn-warning" %>
        </div>
      <% end %>
    <% else %>
      <h2 class="text-center">Nenhum prato cadastrado.</h2>
    <% end %>